name: '🌐 Crowdin localization projects'
labels: ['crowdin']
description: Request the creation of new projects on crowdin.jenkins.io (to localize a plugin) or update its members.

body:
  - type: markdown
    attributes:
      value: |
        Link the GitHub repositories you want to integrate.
  - type: textarea
    attributes:
      label: GitHub repositories
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Management permission allows users to manage the project, languages and general settings.
        This level of permission is not required or recommended for regular translators or proofreaders.
        If you, the issue submitter, are the only person working on the plugin, you only need to add yourself to the list.
        The users can only be added if they logged into crowdin.jenkins.io at least once.
  - type: textarea
    attributes:
      label: Crowdin users to have project management permission
      placeholder: |
        @user1
        @user2
    validations:
      required: true
