name: Notify users based on issue labels
on:
  issues:
    types: [labeled]
#  workflow_run:
#    workflows: ["Auto Labeler"]
#    types:
#      - completed
jobs:
  autonotifier:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1
        with:
          app_id: ${{ secrets.JENKINS_INFRA_HELPDESK_APP_ID }}
          private_key: ${{ secrets.JENKINS_INFRA_HELPDESK_APP_PRIVATE_KEY }}
      - uses: jenschelkopf/issue-label-notification-action@f7d2363e5efa18b8aeea671ca8093e183ae8f218 # 1.3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          recipients: |
            crowdin=@jenkins-infra/crowdin-admins
